In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
customers = pd.read_csv("customers.csv")
restaurants = pd.read_csv("restaurants.csv")
products = pd.read_csv("products.csv")
orders = pd.read_csv("orders.csv")
order_items = pd.read_csv("order_items.csv")
delivery = pd.read_csv("delivery.csv")
delivery_partners = pd.read_csv("delivery_partners.csv")

In [7]:
tables = {
    "customers": customers,
    "restaurants": restaurants,
    "products": products,
    "orders": orders,
    "order_items": order_items,
    "delivery": delivery,
    "delivery_partners": delivery_partners
}

for name, df in tables.items():
    print(f"{name}: {df.shape}")

customers: (5000, 7)
restaurants: (100, 7)
products: (1000, 7)
orders: (30000, 11)
order_items: (62935, 6)
delivery: (29562, 9)
delivery_partners: (300, 6)

In [9]:
for name, df in tables.items():
    print("\n" + "="*50)
    print(name)
    print(df.columns.tolist())

==================================================
customers
['customer_id', 'customer_name', 'gender', 'age', 'city', 'signup_date', 'customer_segment']

==================================================
restaurants
['restaurant_id', 'restaurant_name', 'cuisine_type', 'city', 'rating', 'commission_rate', 'joining_date']

==================================================
products
['product_id', 'restaurant_id', 'product_name', 'category', 'price', 'cost', 'availability']

==================================================
orders
['order_id', 'customer_id', 'restaurant_id', 'order_date', 'order_time', 'order_status', 'payment_method', 'subtotal', 'delivery_fee', 'discount', 'total_amount']

==================================================
order_items
['order_item_id', 'order_id', 'product_id', 'quantity', 'unit_price', 'item_total']

==================================================
delivery
['delivery_id', 'order_id', 'delivery_partner_id', 'pickup_time', 'delivery_time', 'estimated_minutes', 'actual_minutes', 'delivery_status', 'distance_km']

==================================================
delivery_partners
['delivery_partner_id', 'partner_name', 'vehicle_type', 'city', 'joining_date', 'rating']

In [11]:
for name, df in tables.items():
    print(
        name,
        "Duplicate rows:",
        df.duplicated().sum()
    )

customers Duplicate rows: 0
restaurants Duplicate rows: 0
products Duplicate rows: 0
orders Duplicate rows: 0
order_items Duplicate rows: 0
delivery Duplicate rows: 0
delivery_partners Duplicate rows: 0

In [13]:
for name, df in tables.items():
    print("\n" + "="*50)
    print(name)
    print(df.dtypes)

==================================================
customers
customer_id         object
customer_name       object
gender              object
age                  int64
city                object
signup_date         object
customer_segment    object
dtype: object

==================================================
restaurants
restaurant_id       object
restaurant_name     object
cuisine_type        object
city                object
rating             float64
commission_rate    float64
joining_date        object
dtype: object

==================================================
products
product_id        object
restaurant_id     object
product_name      object
category          object
price            float64
cost             float64
availability      object
dtype: object

==================================================
orders
order_id           object
customer_id        object
restaurant_id      object
order_date         object
order_time         object
order_status       object
payment_method     object
subtotal          float64
delivery_fee      float64
discount          float64
total_amount      float64
dtype: object

==================================================
order_items
order_item_id     object
order_id          object
product_id        object
quantity           int64
unit_price       float64
item_total       float64
dtype: object

==================================================
delivery
delivery_id             object
order_id                object
delivery_partner_id     object
pickup_time             object
delivery_time           object
estimated_minutes        int64
actual_minutes           int64
delivery_status         object
distance_km            float64
dtype: object

==================================================
delivery_partners
delivery_partner_id     object
partner_name            object
vehicle_type            object
city                    object
joining_date            object
rating                 float64
dtype: object

In [17]:
for name, df in tables.items():

    text_columns = df.select_dtypes(
        include="object"
    ).columns

    for col in text_columns:
        df[col] = df[col].str.strip()

In [21]:
customers["signup_date"] = pd.to_datetime(
    customers["signup_date"],
    errors="coerce"
)

restaurants["joining_date"] = pd.to_datetime(
    restaurants["joining_date"],
    errors="coerce"
)

orders["order_date"] = pd.to_datetime(
    orders["order_date"],
    errors="coerce"
)

delivery["pickup_time"] = pd.to_datetime(
    delivery["pickup_time"],
    errors="coerce"
)

delivery["delivery_time"] = pd.to_datetime(
    delivery["delivery_time"],
    errors="coerce"
)

In [23]:
orders[
    (orders["subtotal"] < 0) |
    (orders["delivery_fee"] < 0) |
    (orders["discount"] < 0) |
    (orders["total_amount"] < 0)
]

Empty DataFrame
Columns: [order_id, customer_id, restaurant_id, order_date, order_time, order_status, payment_method, subtotal, delivery_fee, discount, total_amount]
Index: []

In [25]:
delivery[
    (delivery["actual_minutes"] < 0) |
    (delivery["estimated_minutes"] < 0)
]

Empty DataFrame
Columns: [delivery_id, order_id, delivery_partner_id, pickup_time, delivery_time, estimated_minutes, actual_minutes, delivery_status, distance_km]
Index: []

In [27]:
products[
    (products["price"] < 0) |
    (products["cost"] < 0)
]

Empty DataFrame
Columns: [product_id, restaurant_id, product_name, category, price, cost, availability]
Index: []

In [29]:
orders["order_month"] = (
    orders["order_date"]
    .dt.to_period("M")
    .astype(str)
)

orders["order_year"] = (
    orders["order_date"].dt.year
)

orders["order_day"] = (
    orders["order_date"].dt.day_name()
)

In [31]:
delivery["delay_minutes"] = (
    delivery["actual_minutes"]
    - delivery["estimated_minutes"]
)

delivery["is_late"] = np.where(
    delivery["actual_minutes"] >
    delivery["estimated_minutes"],
    1,
    0
)

In [33]:
for name, df in tables.items():

    print("\n", name)

    print(
        "Rows:",
        len(df)
    )

    print(
        "Missing values:",
        df.isnull().sum().sum()
    )

    print(
        "Duplicates:",
        df.duplicated().sum()
    )

 customers
Rows: 5000
Missing values: 0
Duplicates: 0

 restaurants
Rows: 100
Missing values: 0
Duplicates: 0

 products
Rows: 1000
Missing values: 0
Duplicates: 0

 orders
Rows: 30000
Missing values: 0
Duplicates: 0

 order_items
Rows: 62935
Missing values: 0
Duplicates: 0

 delivery
Rows: 29562
Missing values: 0
Duplicates: 0

 delivery_partners
Rows: 300
Missing values: 0
Duplicates: 0

In [35]:
customers.to_csv(
    "customers_clean.csv",
    index=False
)

restaurants.to_csv(
    "restaurants_clean.csv",
    index=False
)

products.to_csv(
    "products_clean.csv",
    index=False
)

orders.to_csv(
    "orders_clean.csv",
    index=False
)

order_items.to_csv(
    "order_items_clean.csv",
    index=False
)

delivery.to_csv(
    "delivery_clean.csv",
    index=False
)

delivery_partners.to_csv(
    "delivery_partners_clean.csv",
    index=False
)